<a href="https://colab.research.google.com/github/mamatqobulovsardor/Taxminiy_YouTube_kanal_o-sish_ko-rsatkichlari/blob/main/Taxminiy_YouTube_kanal_o%E2%80%98sish_ko%E2%80%98rsatkichlari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [19]:
#Takrorlanish uchun tasodifiy urug‘ni o‘rnatish
np.random.seed(42)

In [20]:
#2 yil uchun sanalarni yaratish.
start_date = datetime(2019, 8, 19)
end_date = datetime(2024, 12, 13)
date_range = pd.date_range(start=start_date, end=end_date, freq='D')

In [21]:
#Ma'lumotlarni nol bilan boshlash
n_days = len(date_range)
data = {
    'DATE': date_range,
    'SUBSCRIBERS_GAINED': np.zeros(n_days, dtype=int),
    'SUBSCRIBERS_LOST': np.zeros(n_days, dtype=int),
    'VIEWS': np.zeros(n_days, dtype=int),
    'WATCH_HOURS': np.zeros(n_days, dtype=int),
    'LIKES': np.zeros(n_days, dtype=int),
    'SHARES': np.zeros(n_days, dtype=int),
    'COMMENTS': np.zeros(n_days, dtype=int)
}

In [22]:
#DataFrame yaratish
df = pd.DataFrame(data)

In [23]:
#O'sishni yaratish funksiyasi
def generate_growth(start, end, days):
    return np.linspace(start, end, days)

In [24]:
#O‘sish naqshlarini yaratish
subscribers_gained = generate_growth(1, 200, n_days)
subscribers_lost = generate_growth(0, 50, n_days)
views = generate_growth(10, 10000, n_days)
watch_hours = generate_growth(1, 1000, n_days)
likes = generate_growth(0, 500, n_days)
shares = generate_growth(0, 100, n_days)
comments = generate_growth(0, 50, n_days)

In [25]:
#Tasodifiylik qo‘shing va butun son qiymatlarini ta'minlash
for i, col in enumerate(['SUBSCRIBERS_GAINED', 'SUBSCRIBERS_LOST', 'VIEWS', 'WATCH_HOURS', 'LIKES', 'SHARES', 'COMMENTS']):
    random_factor = np.random.normal(1, 0.1, n_days)
    df[col] = np.maximum(0, (eval(col.lower()) * random_factor).astype(int))

In [26]:
#Hafta oxiri ko‘tarilishi
weekend_mask = (df['DATE'].dt.dayofweek >= 5)
df.loc[weekend_mask, ['VIEWS', 'WATCH_HOURS', 'LIKES']] = df.loc[weekend_mask, ['VIEWS', 'WATCH_HOURS', 'LIKES']] * 1.5

<ipython-input-26-dfd78c0a2369>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[   42.     58.5   100.5   112.5   138.    178.5   183.    220.5   274.5
   267.    285.    336.    391.5   432.    405.    333.    423.    517.5
   534.    534.    639.    564.    621.    582.    802.5   748.5   772.5
   603.    771.    655.5  1005.    901.5   970.5   673.5   874.5   997.5
  1015.5  1257.    994.5  1057.5   811.5  1048.5  1210.5  1285.5  1590.
  1234.5  1162.5  1329.   1386.   1227.   1236.   1558.5  1473.   1411.5
  1764.   1228.5  1504.5  1399.5  1714.5  1530.   1821.   1669.5  1924.5
  1599.   1443.   1707.   1891.5  1639.5  1888.5  2098.5  2115.   1951.5
  1471.5  2082.   2068.5  1903.5  2122.5  2115.   2094.   2112.   1998.
  2181.   2329.5  2158.5  2154.   2230.5  1807.5  2263.5  2163.   2196.
  2269.5  2209.5  2677.5  3016.5  2589.   2904.   2646.   2235.   3085.5
  2611.5  2944.5  2767.5  3108.   2872.5  3267.   2841.   2896.5  3066.
  2812.5  2571.   3001.5  3139.5  3138.   2943.   2665.5  3072.   2931.
  3057.   3034.5  3483.   3418.5  3165.   3339.   3318.   3706.5  3987.
  3618.   3238.5  3576.   4200.   3226.5  3369.   3874.5  3706.5  3771.
  4117.5  3807.   3081.   2881.5  4558.5  3907.5  3606.   4086.   4213.5
  3559.5  4374.   3943.5  4341.   4023.   3625.5  3958.5  3198.   3685.5
  4309.5  4305.   3981.   4477.5  3691.5  3939.   4368.   4501.5  4935.
  4951.5  5253.   4666.5  4536.   4917.   4774.5  4719.   4207.5  5050.5
  4650.   5484.   4324.5  3997.5  4954.5  4770.   4240.5  4654.5  5032.5
  5931.   5500.5  5049.   5443.5  4867.5  4917.   5262.   5377.5  5557.5
  5583.   4903.5  5529.   4936.5  5689.5  5718.   4987.5  5788.5  5463.
  5949.   5902.5  4267.5  5454.   5386.5  6030.   5832.   5949.   5644.5
  5446.5  6646.5  5172.   6348.   5973.   4092.   6085.5  5698.5  6648.
  5748.   5745.   5749.5  5385.   5709.   6430.5  6439.5  5065.5  6774.
  6633.   5515.5  6571.5  6358.5  6805.5  6340.5  5974.5  6234.   7212.
  6630.   6604.5  6495.   7078.5  6613.5  6168.   6840.   6729.   6927.
  6919.5  5917.5  6069.   6334.5  6898.5  7198.5  7209.   7501.5  7351.5
  7392.   6846.   5740.5  6240.   6844.5  6786.   7357.5  5655.   6570.
  6892.5  7663.5  5767.5  6550.5  7638.   7188.   7416.   6423.   7723.5
  8332.5  6868.5  7788.   5790.   7845.   7567.5  7396.5  7153.5  7701.
  7537.5  7788.   7155.   8427.   8727.   8961.   7902.   6945.   7773.
  7030.5  7029.   8092.5  7239.   8103.   8787.   8458.5  9127.5  7927.5
  8934.   8100.   9102.   7557.   9585.   8401.5  9241.5  9135.   8224.5
  7767.   8124.   8299.5  7530.   8749.5  6556.5  9861.   8295.   8430.
  9019.5  7854.   8226.   9541.5  9066.   8484.   8764.5  8694.   8109.
  8410.5  9940.5  9486.  10981.5  7399.5  8763.   9966.   8800.5  8004.
  9663.   8764.5  7858.5  9387.   8053.5  9214.5 10137.   8244.  10122.
  7594.5  8637.   8290.5  8629.5  9768.   9589.5 11845.5  9417.   7996.5
 10285.5  8901.   9300.   9985.5 10053.   9025.5  9115.5  9595.5  9519.
  9253.5  8928.  10092.   7792.5  9729.   9129.  10479.  11730.   9540.
  9793.5  9118.5 11787.   9661.5 11142.  10300.5 10939.5 10266.  10320.
 10554.   9744.   9352.5 13347.  12237.  10897.5 11671.5 10614.  11490.
 10465.5  9958.5 10042.5  8859.  12729.   9763.5 11803.5  9405.  11443.5
 10827.  10060.5  9481.5 12277.5  9853.5 12294.  10677.  10570.5 10024.5
 10134.  10288.5 10732.5  9739.5 12274.5 11649.   9183.  10617.  10608.
  9316.5 10605.  11320.5 11982.   9486.  10317.  10333.5 11181.  10021.5
 10162.5  8911.5 12205.5 12525.  11586.  11793.  11733.   9453.  12031.5
 11721.   9925.5 10869.  12807.  10428.  11869.5 13020.  11859.  11518.5
 12759.  11262.  11232.  14166.  12430.5 13272.  13792.5 12946.5 13479.
 11800.5 12360.  14259.  12036.  12409.5 12360.  11886.  11860.5 12256.5
 11613.  10746.  11874.  12693.  13444.5 13365.  11025.  11550.  11866.5
 11734.5 14362.5 11169.  13962.  10656.  15408.  12625.5 13677.  13902.
 11559.  14365.5 13860.  12522.  11742.  15546.  14409.   9523.5 14682.
 14653.5 10882.5 13089.  12949.5 14473.5 13336.5  9928.5 13116.  12129.
 14034.  13935.  12453.  16309.5 12142.5 15391.5 14587.5 13363.5 13723.5
 13596.  15549.  13042.5 11748.  13828.5 12889.5 14316.  13137.  11800.5
 15624.  14389.5 12475.5 14838.  13953.  15402.  14463.  14650.5 14653.5
 13530.  16588.5 13870.5 14398.5 13432.5 13858.5 12885.  14341.5 14334.
 12964.5 12910.5 15243.  13047.  12441.  12163.5 17272.5 15234.  14064.
 17698.5 14434.5 12295.5 11008.5 14356.5 15496.5 16533.  15001.5 16986.
 15178.5 13036.5 14511.  12448.5 14797.5]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[weekend_mask, ['VIEWS', 'WATCH_HOURS', 'LIKES']] = df.loc[weekend_mask, ['VIEWS', 'WATCH_HOURS', 'LIKES']] * 1.5
<ipython-input-26-dfd78c0a2369>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[   6.     4.5   10.5   10.5   15.    16.5   19.5   19.5   24.    25.5
   33.    30.    37.5   28.5   39.    39.    40.5   51.    52.5   40.5
   42.    69.    63.    58.5   70.5   75.    84.    78.    84.    91.5
   85.5   73.5   78.    93.    94.5  103.5   87.   117.   117.   108.
  120.   115.5  136.5  112.5  127.5  111.   135.   114.   145.5  130.5
  142.5  156.   159.   150.   166.5  129.   142.5  133.5  177.   181.5
  192.   144.   178.5  199.5  190.5  171.   198.   174.   174.   165.
  217.5  196.5  198.   214.5  181.5  207.   217.5  192.   237.   189.
  202.5  234.   261.   208.5  219.   276.   238.5  261.   237.   244.5
  228.   226.5  213.   258.   288.   255.   229.5  273.   295.5  261.
  306.   274.5  204.   276.   253.5  352.5  289.5  271.5  247.5  297.
  298.5  360.   288.   316.5  292.5  315.   348.   298.5  304.5  312.
  283.5  295.5  313.5  339.   364.5  337.5  303.   348.   328.5  315.
  373.5  372.   339.   354.   336.   399.   394.5  414.   423.   378.
  406.5  436.5  384.   391.5  388.5  388.5  352.5  370.5  394.5  492.
  388.5  438.   397.5  405.   435.   424.5  420.   445.5  346.5  432.
  381.   475.5  465.   502.5  442.5  367.5  475.5  442.5  481.5  421.5
  394.5  402.   493.5  381.   438.   453.   450.   408.   466.5  424.5
  466.5  517.5  405.   528.   399.   457.5  526.5  574.5  531.   564.
  540.   447.   597.   604.5  618.   537.   577.5  594.   570.   564.
  582.   517.5  555.   531.   619.5  577.5  598.5  640.5  606.   651.
  694.5  546.   474.   561.   666.   568.5  550.5  480.   516.   597.
  609.   552.   651.   604.5  621.   633.   579.   642.   595.5  645.
  571.5  583.5  643.5  648.   555.   735.   468.   595.5  663.   604.5
  594.   610.5  658.5  667.5  616.5  648.   592.5  613.5  595.5  646.5
  777.   699.   744.   724.5  634.5  675.   648.   739.5  580.5  673.5
  742.5  672.   573.   543.   703.5  739.5  841.5  678.   787.5  792.
  738.   714.   789.   733.5  859.5  862.5  874.5  685.5  789.   648.
  648.   760.5  823.5  720.   714.   682.5  732.   757.5  816.   790.5
  790.5  652.5  864.   727.5  885.   735.   766.5  696.   823.5  805.5
  961.5  763.5  762.   777.   829.5  861.   759.   757.5  729.   745.5
  877.5  781.5  756.   781.5  975.   813.   940.5  703.5  748.5  964.5
 1026.  1101.   891.   921.   874.5 1048.5 1023.   712.5  840.   765.
  979.5  993.   936.   972.  1051.5 1030.5  978.   883.5 1105.5  768.
  819.   816.  1077.  1042.5  894.   976.5  819.   831.   781.5  919.5
  882.   961.5  756.  1071.  1036.5 1159.5  903.   936.   924.  1135.5
  970.5  891.  1044.   945.  1003.5 1117.5  909.  1062.   805.5 1000.5
 1063.5 1014.  1146.   684.  1074.   745.5 1087.5  981.  1053.  1020.
 1018.5 1143.  1177.5 1074.  1003.5 1117.5 1017.   835.5 1083.  1099.5
 1143.   969.  1185.  1315.5 1005.  1236.  1408.5 1072.5  966.  1261.5
 1114.5  984.  1165.5 1021.5 1014.  1212.  1036.5 1371.  1033.5 1203.
 1212.  1087.5 1203.  1030.5 1243.5 1240.5 1017.  1141.5 1057.5 1075.5
 1302.  1020.  1015.5 1321.5 1135.5 1098.   996.  1101.  1195.5 1156.5
 1264.5 1060.5 1336.5 1063.5 1212.  1149.  1116.  1305.  1212.  1194.
 1264.5 1261.5 1168.5 1236.  1212.  1047.  1254.  1374.  1416.  1168.5
 1191.  1269.  1194.  1173.  1189.5 1086.  1120.5 1180.5 1459.5 1588.5
 1186.5 1401.  1119.  1120.5 1252.5 1108.5 1209.  1342.5 1488.   984.
 1201.5 1234.5 1381.5 1245.  1218.  1558.5 1302.  1204.5 1521.  1608.
 1267.5  991.5 1296.  1203.  1392.  1323.  1219.5 1276.5 1384.5 1324.5
 1125.  1174.5 1303.5 1129.5 1290.  1174.5 1543.5 1245.  1509.  1440.
 1465.5 1408.5 1557.  1270.5 1296.  1432.5 1318.5 1365.  1227.  1399.5
 1270.5 1281.  1441.5 1536.  1239.  1342.5 1398.  1530.  1558.5 1350.
 1107.  1516.5 1540.5 1506.  1132.5 1467.  1324.5 1300.5 1558.5 1359.
 1650.  1413.  1563.  1570.5 1674.  1440.  1500.  1641.  1432.5 1668.
 1225.5 1518.  1485.  1222.5 1452.  1380.  1587.  1684.5 1503.  1342.5
 1336.5 1581.  1669.5 1629. ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[weekend_mask, ['VIEWS', 'WATCH_HOURS', 'LIKES']] = df.loc[weekend_mask, ['VIEWS', 'WATCH_HOURS', 'LIKES']] * 1.5
<ipython-input-26-dfd78c0a2369>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[  1.5   1.5   4.5   4.5   7.5   6.    9.   10.5   9.   13.5  13.5  13.5
  18.   19.5  19.5  22.5  22.5  22.5  30.   30.   27.   30.   22.5  33.
  30.   37.5  46.5  33.   40.5  34.5  46.5  34.5  40.5  36.   40.5  42.
  48.   54.   51.   52.5  61.5  48.   60.   49.5  66.   48.   54.   66.
  66.   57.   69.   84.   76.5  67.5  85.5  79.5  82.5  78.   81.   73.5
  82.5  96.   99.  103.5  93.   88.5  90.   90.  102.   70.5  84.   96.
 106.5  96.   99.   99.   96.   90.  100.5 112.5 111.   93.  112.5 108.
 117.  114.  111.  127.5 114.  108.  136.5 138.  102.  111.  115.5 103.5
 135.  127.5 129.  145.5 144.  141.  117.  144.  141.  151.5 136.5 123.
 136.5 145.5 175.5 160.5 141.  145.5 105.  160.5 168.  169.5 162.  177.
 183.  154.5 148.5 172.5 172.5 195.  181.5 180.  187.5 174.  193.5 159.
 204.  166.5 174.  163.5 189.  180.  145.5 184.5 210.  180.  177.  216.
 214.5 199.5 214.5 243.  222.  231.  174.  243.  189.  225.  166.5 181.5
 207.  213.  237.  223.5 217.5 274.5 232.5 249.  244.5 222.  195.  216.
 234.  219.  199.5 210.  262.5 237.  246.  234.  243.  255.  274.5 184.5
 268.5 219.  234.  235.5 249.  271.5 237.  271.5 268.5 235.5 274.5 315.
 244.5 232.5 243.  207.  303.  234.  282.  253.5 270.  324.  289.5 255.
 297.  292.5 333.  273.  298.5 282.  258.  322.5 258.  237.  264.  249.
 343.5 303.  297.  354.  276.  315.  298.5 336.  304.5 342.  319.5 345.
 322.5 315.  370.5 246.  319.5 312.  304.5 294.  376.5 240.  322.5 291.
 348.  316.5 349.5 306.  292.5 373.5 372.  340.5 298.5 300.  327.  396.
 399.  331.5 382.5 399.  363.  361.5 381.  361.5 360.  372.  351.  313.5
 381.  366.  318.  349.5 334.5 352.5 481.5 399.  298.5 310.5 343.5 429.
 364.5 301.5 352.5 424.5 330.  334.5 384.  412.5 331.5 372.  433.5 342.
 363.  307.5 372.  429.  421.5 412.5 403.5 412.5 405.  421.5 439.5 349.5
 382.5 387.  468.  433.5 381.  397.5 345.  331.5 342.  430.5 432.  384.
 409.5 442.5 333.  409.5 423.  426.  382.5 519.  442.5 391.5 460.5 466.5
 457.5 517.5 393.  436.5 450.  429.  402.  547.5 465.  405.  463.5 397.5
 439.5 499.5 489.  387.  529.5 430.5 492.  453.  543.  435.  462.  384.
 508.5 508.5 465.  520.5 484.5 466.5 489.  556.5 534.  496.5 483.  504.
 502.5 507.  481.5 534.  459.  484.5 516.  457.5 534.  544.5 484.5 444.
 519.  573.  541.5 489.  447.  514.5 460.5 495.  543.  570.  513.  589.5
 523.5 550.5 535.5 537.  567.  525.  514.5 502.5 561.  516.  504.  528.
 483.  550.5 598.5 519.  520.5 529.5 540.  633.  463.5 631.5 522.  534.
 601.5 472.5 622.5 570.  472.5 474.  558.  597.  469.5 516.  549.  523.5
 664.5 544.5 729.  558.  612.  559.5 519.  637.5 561.  646.5 607.5 606.
 609.  699.  612.  637.5 612.  603.  585.  502.5 571.5 601.5 612.  634.5
 589.5 685.5 688.5 631.5 586.5 627.  649.5 655.5 621.  681.  522.  612.
 693.  592.5 574.5 643.5 717.  609.  592.5 666.  741.  553.5 666.  606.
 618.  652.5 574.5 597.  598.5 738.  528.  625.5 609.  619.5 697.5 600.
 646.5 643.5 607.5 646.5 657.  673.5 565.5 676.5 678.  675.  745.5 712.5
 597.  789.  508.5 600.  751.5 658.5 612.  619.5 760.5 573.  591.  658.5
 673.5 729.  723.  669.  664.5 666.  622.5 726.  502.5 721.5 798.  598.5
 739.5 555.  708.  669.  793.5 717.  606.  742.5 738.  781.5 724.5 775.5
 861.  858.  711.  825.  724.5 705.  804.  772.5 591.  820.5 685.5 822.
 759.  655.5 754.5 733.5 808.5 597.  925.5 723.  631.5 723.  861.  819.
 721.5 781.5]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[weekend_mask, ['VIEWS', 'WATCH_HOURS', 'LIKES']] = df.loc[weekend_mask, ['VIEWS', 'WATCH_HOURS', 'LIKES']] * 1.5

In [27]:
#Mavsumiy o‘zgarish (yozda yuqori)
days_in_year = 366
summer_boost = np.sin(np.linspace(0,2*np.pi, days_in_year))
df['VIEWS'] = df['VIEWS'] * (1 + 0.2 * summer_boost[df['DATE'].dt.dayofyear - 1])

In [28]:
#Ba'zan viral videolar (o‘rtacha har 2 oyda bir marta, ikkinchi oydan boshlab)
viral_days = np.random.choice(range(30, n_days), size=11, replace=False)
df.loc[viral_days, ['VIEWS', 'LIKES', 'SHARES', 'COMMENTS']] = df.loc[viral_days, ['VIEWS', 'LIKES', 'SHARES', 'COMMENTS']] * 5

In [29]:
#Butun son qiymatlarini ta'minlash
for col in df.columns:
    if col !='DATE':
        df[col] = df[col].astype(int)

In [30]:
#Kumulativ obunachilarni hisoblash
df['TOTAL_SUBSCRIBERS'] = (df['SUBSCRIBERS_GAINED'] - df['SUBSCRIBERS_LOST']).cumsum()

In [31]:
#Manfiy qiymatlar yo'qligini ta'minlash
df[df.select_dtypes(include=[np.number]).columns] = df.select_dtypes(include=[np.number]).clip(lower=0)

In [32]:
#CSV shaklda saqlash
df.to_csv('youtube_channel_data.csv', index=False)

In [33]:
#DataFrame-ni ko'rsatish
df

,DATE,SUBSCRIBERS_GAINED,SUBSCRIBERS_LOST,VIEWS,WATCH_HOURS,LIKES,SHARES,COMMENTS,TOTAL_SUBSCRIBERS
0,2019-08-19,1,0,8,0,0,0,0,1
1,2019-08-20,1,0,13,1,0,0,0,2
2,2019-08-21,1,0,17,2,0,0,0,3
3,2019-08-22,1,0,22,2,0,0,0,4
4,2019-08-23,1,0,23,2,0,0,0,5
...,...,...,...,...,...,...,...,...,...
1939,2024-12-09,201,45,9272,977,495,95,56,147311
1940,2024-12-10,205,49,9426,969,512,91,54,147467
1941,2024-12-11,191,52,10583,1043,446,93,53,147606
1942,2024-12-12,205,38,9131,1081,529,115,53,147773
1943,2024-12-13,193,49,9277,1060,469,93,55,147917